Test good build

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -15,6 +15,18 @@ inputs:
     description: "Branch On Orangefox For Sync"
     required: true
     default: "12.1"
+  KERNEL_TREE:
+    description: 'Kernel Tree On Your Device'
+    required: false
+    default: ''
+  KERNEL_BRANCH:
+    description: 'Branch On Your Kernel Tree'
+    required: false
+    default: ''
+  KERNEL_PATH:
+    description: 'Path On Your Kernel Directory'
+    required: false
+    default: 'kernel/vivo/1938'
   DEVICE_TREE:
     description: 'OrangeFox Device Tree'
     required: true
@@ -35,6 +47,26 @@ inputs:
     description: 'Specify Your Build Target [boot, recovery, vendorboot'
     required: true
     default: 'recovery'
+  COMMON_TREE:
+    description: 'Common Tree On Your Device'
+    required: false
+    default: ''
+  COMMON_BRANCH:
+    description: 'Branch On Your Common Tree'
+    required: false
+    default: ''
+  COMMON_PATH:
+    description: 'Path On Your Common Directory'
+    required: false
+    default: 'common/vivo/1938'
+  TG_CHAT_ID:
+    description: 'Telegram Chat ID'
+    required: false
+    default: '${{ secrets.TG_CHAT_ID }}'
+  TG_TOKEN:
+    description: 'Telegram Bot Token'
+    required: false
+    default: '${{ secrets.TG_TOKEN }}'
 
 runs:
   using: 'composite'
@@ -56,33 +88,61 @@ runs:
         cd scripts
         sudo bash setup/android_build_env.sh
 
-    - name: 🎡 Set-up Manifest
+    - name: 🎡 Set-up Manifest Sync
       shell: bash
       run: |
+        source config.sh
+        telegram_message() {
+            curl -s -X POST "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" \
+            -d chat_id="${TG_CHAT_ID}" \
+            -d parse_mode="HTML" \
+            -d text="$1"
+        }
         mkdir -p ${GITHUB_WORKSPACE}/OrangeFox && cd ${GITHUB_WORKSPACE}/OrangeFox
         git config --global user.name "${{ github.actor }}"
         git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
         git clone ${{ inputs.FOX_SYNC }} && cd sync
         ./orangefox_sync.sh --branch ${{ inputs.FOX_SYNC_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}
         cp -r ${GITHUB_WORKSPACE}/maintainer.png ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}/bootable/recovery/gui/theme/portrait_hdpi/images/Default/About
-
-    - name: 📥 Clone Device Tree
-      shell: bash
-      run: |
         cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}
         git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./${{ inputs.DEVICE_PATH }}
         cd ${{ inputs.DEVICE_PATH }}
         echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
+        if [[ ! -d bootable/recovery/gui/theme ]]; then
+            git clone https://gitlab.com/OrangeFox/misc/theme.git bootable/recovery/gui/theme || { echo "ERROR: Failed to Clone the OrangeFox Theme!" && exit 1; }
+        fi
+        if [[ ! -z "${{ inputs.KERNEL_TREE }}" ]]; then
+            git clone ${{ inputs.KERNEL_TREE }} -b ${{ inputs.KERNEL_BRANCH }} ${{ inputs.KERNEL_PATH }}
+        fi
+        if [[ ! -z "${{ inputs.COMMON_TREE }}" ]]; then
+            git clone ${{ inputs.COMMON_TREE }} -b ${{ inputs.COMMON_BRANCH }} ${{ inputs.COMMON_PATH }}
+        fi
 
     - name: 🦊 Building OrangeFox
       shell: bash
       run: |
+        source config.sh
+        timeStart
         cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}
+        telegram_message
+        export LC_ALL="C"
+        BUILDLOG="${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}/build.log"
+        build_message "Prepare for build..."
         set +e
-        source build/envsetup.sh
+        . build/envsetup.sh
         export ALLOW_MISSING_DEPENDENCIES=true
         set -e
-        lunch twrp_${{ inputs.DEVICE_NAME }}-eng && make clean && mka adbd ${{ inputs.BUILD_TARGET }}image
+        build_message "lunch twrp_${{ inputs.DEVICE_NAME }}-eng"
+        lunch twrp_${{ inputs.DEVICE_NAME }}-engmake
+        mkfifo reading
+        tee "${BUILDLOG}" < reading &
+        build_message "Staring bro...🔥"
+        sleep 2
+        build_message "🛠️ Building..."
+        progress |& mka adbd ${{ inputs.BUILD_TARGET }}image -j$(nproc --all) > reading || { echo "ERROR: Failed to Build OrangeFox!" && exit 1; }
+        retVal=$?
+        timeEnd
+        statusBuild
 
     - name: 📝 Set Release Properties
       shell: bash
